### ISSUE TITLE
Unable to fetch League

### ISSUE THREAD

**Issue by CowboyKillers** [rbarton65/espnff#48]
Getting:

>>> league = League(719284, 2017)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Ash/Downloads/espnff-master/espnff/league.py", line 22, in __init__
    self._fetch_league()
  File "/Users/Ash/Downloads/espnff-master/espnff/league.py", line 42, in _fetch_league
    data = r.json()
  File "/anaconda/lib/python3.6/site-packages/requests/models.py", line 877, in json
    self.content.decode(encoding), **kwargs
  File "/anaconda/lib/python3.6/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/anaconda/lib/python3.6/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/anaconda/lib/python3.6/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>>

**Comment by earlejam** [comment]
I just opened an issue for a similar problem, only that is says ```Expecting value: line 2 column 2 (char 2)```. Did you ever resolve this? If so, how?

**Comment by danabrey** [comment]
@earlejam Same issue as #59, unrelated to this issue.
